FROM python:3.8.13 as base
RUN mkdir /code

ADD requirements.txt .
RUN pip install -r requirements.txt

ADD ./ /src/

WORKDIR /src

FROM base as build
ENTRYPOINT ["uvicorn", "app:app","--reload ","--host=0.0.0.0", "--port","15400"]